package dialogue.DialoguePackage;


/**
* dialogue/DialoguePackage/notExistingPseudo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/leocorone/Documents/workspace/eclipse_luna/corba pull avance/src/dialogue.idl
* vendredi 17 octobre 2014 20 h 21 CEST
*/

public final class notExistingPseudo extends org.omg.CORBA.UserException
{
  public String detail = null;

  public notExistingPseudo ()
  {
    super(notExistingPseudoHelper.id());
  } // ctor

  public notExistingPseudo (String _detail)
  {
    super(notExistingPseudoHelper.id());
    detail = _detail;
  } // ctor


  public notExistingPseudo (String $reason, String _detail)
  {
    super(notExistingPseudoHelper.id() + "  " + $reason);
    detail = _detail;
  } // ctor

} // class notExistingPseudo
