package dialogue;


/**
* dialogue/ConnectionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/leocorone/Documents/workspace/eclipse_luna/corba pull avance/src/dialogue.idl
* mardi 4 novembre 2014 11 h 53 CET
*/

public interface ConnectionOperations 
{
  dialogue.Dialogue connect (String pseudo);
  void disconnect (String pseudo) throws dialogue.notExistingPseudo;
} // interface ConnectionOperations
