package dialogue;

/**
* dialogue/ConnectionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/leocorone/Documents/workspace/eclipse_luna/corba pull avance/src/dialogue.idl
* mardi 4 novembre 2014 11 h 53 CET
*/

public final class ConnectionHolder implements org.omg.CORBA.portable.Streamable
{
  public dialogue.Connection value = null;

  public ConnectionHolder ()
  {
  }

  public ConnectionHolder (dialogue.Connection initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dialogue.ConnectionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dialogue.ConnectionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dialogue.ConnectionHelper.type ();
  }

}
