package dialogue;


/**
* dialogue/DialogueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/leocorone/Documents/workspace/eclipse_luna/corba pull avance/src/dialogue.idl
* mardi 4 novembre 2014 11 h 53 CET
*/

public interface DialogueOperations 
{
  String[] getClients ();
  void sendMessage (String to, String message) throws dialogue.notExistingPseudo;
  String[] getMessage ();
} // interface DialogueOperations
