
/**
* HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/leocorone/Downloads/HelloWorld/Hello.idl
* mardi 14 octobre 2014 14 h 09 CEST
*/

public interface HelloOperations 
{
  String SayHello ();
} // interface HelloOperations
