
/**
* Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/leocorone/Downloads/HelloWorld/Hello.idl
* mardi 14 octobre 2014 14 h 09 CEST
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
