package dialogue;

/**
* dialogue/DialogueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/leocorone/Documents/workspace/eclipse_luna/coba/src/dialogue.idl
* mercredi 15 octobre 2014 12 h 08 CEST
*/

public final class DialogueHolder implements org.omg.CORBA.portable.Streamable
{
  public dialogue.Dialogue value = null;

  public DialogueHolder ()
  {
  }

  public DialogueHolder (dialogue.Dialogue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dialogue.DialogueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dialogue.DialogueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dialogue.DialogueHelper.type ();
  }

}
