package dialogue;


/**
* dialogue/Dialogue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/leocorone/Documents/workspace/eclipse_luna/coba/src/dialogue.idl
* mercredi 15 octobre 2014 12 h 08 CEST
*/

public interface Dialogue extends DialogueOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Dialogue
