package dialogue;


/**
* dialogue/DialogueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/leocorone/Documents/workspace/eclipse_luna/coba/src/dialogue.idl
* mercredi 15 octobre 2014 12 h 08 CEST
*/

public interface DialogueOperations 
{
  void connect (String pseudo);
  void disconnect (String pseudo);
  String[] getClients ();
  void sendMessage (String from, String to, String message) throws dialogue.DialoguePackage.notExistingPseudo;
  String getMessage (String pseudo);
} // interface DialogueOperations
